# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1js8_O0md1lhOLDTbexTB8bQbi7Z_22uO
"""

!pip install librosa

import librosa
import librosa.display
import numpy as np
import matplotlib.pyplot as plt


def generate_spectrogram(wav_file):
    """
    Generates and displays a spectrogram for a given audio file.

    Args:
        wav_file (str): Path to the audio file.
    """

    # Load audio file using librosa
    data, sample_rate = librosa.load(wav_file)

    # Create a spectrogram using librosa.display.specshow
    plt.figure(figsize=(12, 6))
    librosa.display.specshow(librosa.amplitude_to_db(np.abs(librosa.stft(data)), ref=np.max),
                             sr=sample_rate,
                             x_axis='time',
                             y_axis='linear')

    plt.title(f'Spectrogram of {wav_file}')
    plt.xlabel('Time (s)')
    plt.ylabel('Frequency (Hz)')
    plt.colorbar(format='%+2.0f dB')
    plt.tight_layout()
    plt.show()

# Example usage
wav_file_path = 'music.wav'  # Replace with your WAV file path
generate_spectrogram(wav_file_path)

!pip install gtts

from gtts import gTTS
import os

# Matnni belgilash
text = "trading soxasiga yaxshi summa bilan kirmasa foyda olish qiyin ."

# Ovoz yaratish (gTTS - Google Text-to-Speech)
language = 'en'  # Changed to English ('en')
tts = gTTS(text=text, lang=language, slow=False)

# Ovoz faylini saqlash
audio_file = "output.mp3"
tts.save(audio_file)

# Ovoz faylini tinglash (Google Colab-da)
from IPython.display import Audio
Audio(audio_file)

!pip install librosa

import librosa
import librosa.display
import numpy as np
import matplotlib.pyplot as plt


def generate_spectrogram(wav_file):
    """
    Generates and displays a spectrogram for a given audio file.

    Args:
        wav_file (str): Path to the audio file.
    """

    # Load audio file using librosa
    data, sample_rate = librosa.load(wav_file)

    # Create a spectrogram using librosa.display.specshow
    plt.figure(figsize=(12, 6))
    librosa.display.specshow(librosa.amplitude_to_db(np.abs(librosa.stft(data)), ref=np.max),
                             sr=sample_rate,
                             x_axis='time',
                             y_axis='linear')

    plt.title(f'Spectrogram of {wav_file}')
    plt.xlabel('Time (s)')
    plt.ylabel('Frequency (Hz)')
    plt.colorbar(format='%+2.0f dB')
    plt.tight_layout()
    plt.show()

# Example usage
wav_file_path = 'musiqa.wav'  # Replace with your WAV file path
generate_spectrogram(wav_file_path)

!pip install librosa




from gtts import gTTS
import os

# Matnni belgilash
text = "jiyan togangga suyan."

# Ovoz yaratish (gTTS - Google Text-to-Speech)
language = 'en'  # Changed to English ('en')
tts = gTTS(text=text, lang=language, slow=False)

# Ovoz faylini saqlash
audio_file = "output.mp3"
tts.save(audio_file)

# Ovoz faylini tinglash (Google Colab-da)
from IPython.display import Audio
Audio(audio_file)

!pip install librosa

import librosa
import librosa.display
import numpy as np
import matplotlib.pyplot as plt


def generate_spectrogram(wav_file):
    """
    Generates and displays a spectrogram for a given audio file.

    Args:
        wav_file (str): Path to the audio file.
    """

    # Load audio file using librosa
    data, sample_rate = librosa.load(wav_file)

    # Create a spectrogram using librosa.display.specshow
    plt.figure(figsize=(12, 6))
    librosa.display.specshow(librosa.amplitude_to_db(np.abs(librosa.stft(data)), ref=np.max),
                             sr=sample_rate,
                             x_axis='time',
                             y_axis='linear')

    plt.title(f'Spectrogram of {wav_file}')
    plt.xlabel('Time (s)')
    plt.ylabel('Frequency (Hz)')
    plt.colorbar(format='%+2.0f dB')
    plt.tight_layout()
    plt.show()

# Example usage
wav_file_path = 'qoshiq.wav'  # Replace with your WAV file path
generate_spectrogram(wav_file_path)

!pip install librosa




from gtts import gTTS
import os

# Matnni belgilash
text = "choq 100 dollar choq choq 200 dollar."

# Ovoz yaratish (gTTS - Google Text-to-Speech)
language = 'en'  # Changed to English ('en')
tts = gTTS(text=text, lang=language, slow=False)

# Ovoz faylini saqlash
audio_file = "output.mp3"
tts.save(audio_file)

# Ovoz faylini tinglash (Google Colab-da)
from IPython.display import Audio
Audio(audio_file)